### ISSUE TITLE
File Upload Button

### ISSUE THREAD

**Issue by jiminyk** [xixmia/insurance-nation#3]
# WTB File Upload Button
### Simple Forms Info

SimpleForms works by giving you an API token and that becomes you account. [Click here to go to the form page associated with the account.](https://getsimpleform.com/instructions?api_token=11e07651594ecdc0e3fe0487f3f90250)

**Comment by ralphdp** [comment]
Okay super simple solution..
The form tag will need enctype="multipart/form-data" added to it at this point and that should be it..
http://blog.getsimpleform.com/2012/07/20/we-have-added-file-uploads-to-simple-form

**Comment by jiminyk** [comment]
Beautiful, I like simple solutions!
